services:
  web:
    image: nginx:1.27
    volumes:
      - ./templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    ports:
      - "9090:80"
    environment:
      - NGINX_HOST=big-data-chart.local
      - NGINX_PORT=80
      - NGINX_BACKEND_PORT=8080
